INSERT INTO galeri (foto, kategori, caption, urutan) VALUES
('/images/galeri/bakti-sosial-1.jpg', 'Sosial', 'Kegiatan bakti sosial Yasuki bersama warga sekitar', 10),
('/images/galeri/bakti-sosial-kesehatan.jpg', 'Sosial', 'Bakti sosial bidang kesehatan untuk warga dhuafa', 20),
('/images/galeri/bencana-semeru-1.jpg', 'Sosial', 'Bantuan kemanusiaan untuk korban bencana Semeru', 30),
('/images/galeri/bencana-semeru-2.jpg', 'Sosial', 'Penyaluran bantuan tahap lanjutan untuk korban bencana Semeru', 40),
('/images/galeri/peduli-cianjur-1.jpg', 'Sosial', 'Program Peduli Cianjur — bantuan kemanusiaan pascabencana', 50),
('/images/galeri/peduli-cianjur-2.jpg', 'Sosial', 'Distribusi bantuan Peduli Cianjur kepada warga terdampak', 60),
('/images/galeri/peduli-cianjur-3.jpg', 'Sosial', 'Tim Yasuki di lapangan program Peduli Cianjur', 70),
('/images/galeri/peduli-cianjur-4.jpg', 'Sosial', 'Penyerahan bantuan logistik program Peduli Cianjur', 80),
('/images/galeri/peduli-cianjur-5.jpg', 'Sosial', 'Dokumentasi kegiatan Peduli Cianjur bersama warga', 90),
('/images/galeri/peduli-cianjur-6.jpg', 'Sosial', 'Suasana penyaluran bantuan program Peduli Cianjur', 100),
('/images/galeri/qurban-2023.jpg', 'Sosial', 'Penyembelihan dan distribusi hewan qurban tahun 2023', 110),
('/images/galeri/qurban-2025-1.jpg', 'Sosial', 'Kegiatan Qurban 2025 — persiapan penyembelihan', 120),
('/images/galeri/qurban-2025-2.jpg', 'Sosial', 'Kegiatan Qurban 2025 — proses pemotongan daging', 130),
('/images/galeri/qurban-2025-3.jpg', 'Sosial', 'Kegiatan Qurban 2025 — pengemasan daging qurban', 140),
('/images/galeri/qurban-2025-4.jpg', 'Sosial', 'Kegiatan Qurban 2025 — distribusi ke warga dhuafa', 150),
('/images/galeri/berbagi-takjil-1.jpg', 'Sosial', 'Pembagian takjil gratis untuk warga dan musafir', 160),
('/images/galeri/berbagi-takjil-2.jpg', 'Sosial', 'Kegiatan berbagi takjil di bulan Ramadhan', 170),
('/images/galeri/shobarumat-1.jpg', 'Sosial', 'Shobarumat — donasi barang layak pakai untuk umat', 180),
('/images/galeri/shobarumat-2.jpg', 'Sosial', 'Proses sortir dan distribusi Shobarumat', 190),
('/images/galeri/wakaf-alquran-galeri.jpg', 'Keagamaan', 'Penyerahan wakaf Al-Qur''an untuk masjid dan TPQ', 200),
('/images/galeri/anak-binaan-2.jpg', 'Pendidikan', 'Keseharian anak binaan Yasuki', 210),
('/images/galeri/outbond-anak-binaan.jpg', 'Pendidikan', 'Kegiatan outbond untuk anak binaan Yasuki', 220),
('/images/galeri/anak-binaan-belajar-dagang.jpg', 'Pendidikan', 'Pelatihan kewirausahaan/belajar berdagang untuk anak binaan', 230),
('/images/galeri/anak-binaan-hari-santri.jpg', 'Pendidikan', 'Peringatan Hari Santri bersama anak binaan', 240),
('/images/galeri/tpq-sore-1.jpg', 'Pendidikan', 'Kegiatan TPQ sore — belajar mengaji', 250),
('/images/galeri/tpq-sore-2.jpg', 'Pendidikan', 'Santri TPQ sore Yasuki', 260),
('/images/galeri/tpq-sore-3.jpg', 'Pendidikan', 'Suasana belajar TPQ sore', 270),
('/images/galeri/tpq-sore-4.jpg', 'Pendidikan', 'Kegiatan mengaji TPQ sore', 280),
('/images/galeri/tpq-sore-5.jpg', 'Pendidikan', 'Pembinaan santri TPQ sore', 290),
('/images/galeri/tpq-sore-6.jpg', 'Pendidikan', 'Aktivitas TPQ sore Yasuki', 300),
('/images/galeri/tpq-sore-7.jpg', 'Pendidikan', 'Dokumentasi TPQ sore', 310),
('/images/galeri/hadrah-anak-1.jpg', 'Pendidikan', 'Latihan hadrah anak binaan Yasuki', 320),
('/images/galeri/hadrah-anak-2.jpg', 'Pendidikan', 'Penampilan hadrah anak binaan', 330),
('/images/galeri/hadrah-anak-3.jpg', 'Pendidikan', 'Kegiatan seni hadrah anak-anak', 340),
('/images/galeri/hadrah-anak-4.jpg', 'Pendidikan', 'Grup hadrah binaan Yasuki tampil', 350),
('/images/galeri/program-susu-sehat-1.jpg', 'Pendidikan', 'Program Susu Sehat untuk tumbuh kembang anak binaan', 360),
('/images/galeri/program-susu-sehat-2.jpg', 'Pendidikan', 'Pembagian susu sehat kepada anak binaan', 370),
('/images/galeri/olahraga-bersama.jpg', 'Pendidikan', 'Olahraga kebugaran bersama anak binaan', 380),
('/images/galeri/istighosah-galeri.jpg', 'Keagamaan', 'Istighosah dan doa bersama warga sekitar', 390),
('/images/galeri/ziarah-wisata-religi.jpg', 'Keagamaan', 'Kegiatan ziarah wisata religi bersama anak binaan', 400),
('/images/galeri/bersih-masjid.jpg', 'Keagamaan', 'Kerja bakti bersih-bersih masjid', 410),
('/images/galeri/pembangunan-masjid-galeri.jpg', 'Pembangunan', 'Progres pembangunan Masjid Darussalam', 420),
('/images/galeri/panti-yatim.jpg', 'Pembangunan', 'Bangunan panti asuhan yatim piatu Yasuki', 430),
('/images/galeri/kebun-thoyyibah.jpg', 'Pertanian', 'Kebun Tanaman Thoyyibah — bagian dari program pertanian Yasuki', 440),
('/images/galeri/pengurus-yasuki.jpg', 'Organisasi', 'Kebersamaan pengurus Yasuki', 450),
('/images/galeri/halal-bihalal.jpg', 'Organisasi', 'Halal bihalal pengurus dan admin Yasuki', 460),
('/images/galeri/kegiatan-bersama-1.jpg', 'Organisasi', 'Kegiatan kebersamaan Yasuki dengan anak binaan dan warga', 470),
('/images/galeri/silaturahmi-ibu-ibu.jpg', 'Organisasi', 'Silaturahmi bersama ibu-ibu di lingkungan Yasuki', 480),
('/images/galeri/kegiatan-halaman-yayasan.jpg', 'Organisasi', 'Anak binaan berkumpul di halaman Yayasan', 490),
('/images/galeri/buka-puasa-bersama.jpg', 'Keagamaan', 'Buka puasa bersama anak binaan dan warga', 500),
('/images/galeri/gebyar-ramadhan.jpg', 'Keagamaan', 'Gebyar Ramadhan — pembagian bingkisan untuk anak binaan', 510),
('/images/galeri/kegiatan-anak-binaan-berbusana.jpg', 'Pendidikan', 'Anak binaan Yasuki dalam kegiatan bertema busana muslim', 520),
('/images/galeri/hut-yayasan.jpg', 'Organisasi', 'Peringatan HUT ke-4 Yayasan Sosial Umi Kulsum Indonesia', 530);
